powershell build\build.ps1 -Script build\build.cake -Target Build

output\build\Disruptor.PerfTests.exe Disruptor.PerfTests.Raw.OneToOneRawBatchThroughputTest
output\build\Disruptor.PerfTests.exe Disruptor.PerfTests.Raw.OneToOneRawThroughputTest
output\build\Disruptor.PerfTests.exe Disruptor.PerfTests.Sequenced.OneToOneSequencedBatchThroughputTest
output\build\Disruptor.PerfTests.exe Disruptor.PerfTests.Sequenced.OneToOneSequencedLongArrayThroughputTest
output\build\Disruptor.PerfTests.exe Disruptor.PerfTests.Sequenced.OneToOneSequencedPollerThroughputTest
output\build\Disruptor.PerfTests.exe Disruptor.PerfTests.Sequenced.OneToOneSequencedThroughputTest
output\build\Disruptor.PerfTests.exe Disruptor.PerfTests.Translator.OneToOneTranslatorThroughputTest
output\build\Disruptor.PerfTests.exe Disruptor.PerfTests.Sequenced.OneToThreeDiamondSequencedThroughputTest
output\build\Disruptor.PerfTests.exe Disruptor.PerfTests.Sequenced.OneToThreePipelineSequencedThroughputTest
output\build\Disruptor.PerfTests.exe Disruptor.PerfTests.WorkHandler.OneToThreeReleasingWorkerPoolThroughputTest
output\build\Disruptor.PerfTests.exe Disruptor.PerfTests.Sequenced.OneToThreeSequencedThroughputTest
output\build\Disruptor.PerfTests.exe Disruptor.PerfTests.WorkHandler.OneToThreeWorkerPoolThroughputTest
output\build\Disruptor.PerfTests.exe Disruptor.PerfTests.Sequenced.ThreeToOneSequencedBatchThroughputTest
output\build\Disruptor.PerfTests.exe Disruptor.PerfTests.Sequenced.ThreeToOneSequencedThroughputTest
output\build\Disruptor.PerfTests.exe Disruptor.PerfTests.Sequenced.ThreeToThreeSequencedThroughputTest
output\build\Disruptor.PerfTests.exe Disruptor.PerfTests.WorkHandler.TwoToTwoWorkProcessorThroughputTest

pause