//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("https://github.com/disruptor-net/Disruptor-net")]
[assembly: AssemblyProduct("Disruptor")]
[assembly: AssemblyCopyright("Copyright © disruptor-net")]
[assembly: AssemblyVersion("3.3.4")]
[assembly: AssemblyFileVersion("3.3.4")]


