//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.488
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("http://github.com/odeheurles/Disruptor-net/network")]
[assembly: AssemblyProduct("Disruptor")]
[assembly: AssemblyCopyright("Copyright © disruptor-net")]
[assembly: AssemblyVersion("0.1")]
[assembly: AssemblyFileVersion("0.1")]


